//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace blazordatagrid.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SyncfusionBlazorLocale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SyncfusionBlazorLocale() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("blazordatagrid.Resources.SyncfusionBlazorLocale", typeof(SyncfusionBlazorLocale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Dialog_Close {
            get {
                return ResourceManager.GetString("Dialog_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string InPlaceEditor_Cancel {
            get {
                return ResourceManager.GetString("InPlaceEditor_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditAreaClick.
        /// </summary>
        public static string InPlaceEditor_EditAreaClick {
            get {
                return ResourceManager.GetString("InPlaceEditor_EditAreaClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditAreaDoubleClick.
        /// </summary>
        public static string InPlaceEditor_EditAreaDoubleClick {
            get {
                return ResourceManager.GetString("InPlaceEditor_EditAreaDoubleClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditIcon.
        /// </summary>
        public static string InPlaceEditor_EditIcon {
            get {
                return ResourceManager.GetString("InPlaceEditor_EditIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoadingText.
        /// </summary>
        public static string InPlaceEditor_LoadingText {
            get {
                return ResourceManager.GetString("InPlaceEditor_LoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string InPlaceEditor_Save {
            get {
                return ResourceManager.GetString("InPlaceEditor_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddTitle.
        /// </summary>
        public static string Kanban_AddTitle {
            get {
                return ResourceManager.GetString("Kanban_AddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Kanban_Cancel {
            get {
                return ResourceManager.GetString("Kanban_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CardsSelected.
        /// </summary>
        public static string Kanban_CardsSelected {
            get {
                return ResourceManager.GetString("Kanban_CardsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Kanban_Delete {
            get {
                return ResourceManager.GetString("Kanban_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteContent.
        /// </summary>
        public static string Kanban_DeleteContent {
            get {
                return ResourceManager.GetString("Kanban_DeleteContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteTitle.
        /// </summary>
        public static string Kanban_DeleteTitle {
            get {
                return ResourceManager.GetString("Kanban_DeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditTitle.
        /// </summary>
        public static string Kanban_EditTitle {
            get {
                return ResourceManager.GetString("Kanban_EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        public static string Kanban_Items {
            get {
                return ResourceManager.GetString("Kanban_Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        public static string Kanban_Max {
            get {
                return ResourceManager.GetString("Kanban_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        public static string Kanban_Min {
            get {
                return ResourceManager.GetString("Kanban_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Kanban_No {
            get {
                return ResourceManager.GetString("Kanban_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Kanban_Save {
            get {
                return ResourceManager.GetString("Kanban_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Kanban_Yes {
            get {
                return ResourceManager.GetString("Kanban_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string RecurrenceEditor_Count {
            get {
                return ResourceManager.GetString("RecurrenceEditor_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        public static string RecurrenceEditor_Daily {
            get {
                return ResourceManager.GetString("RecurrenceEditor_Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        public static string RecurrenceEditor_Days {
            get {
                return ResourceManager.GetString("RecurrenceEditor_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string RecurrenceEditor_End {
            get {
                return ResourceManager.GetString("RecurrenceEditor_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every.
        /// </summary>
        public static string RecurrenceEditor_Every {
            get {
                return ResourceManager.GetString("RecurrenceEditor_Every", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        public static string RecurrenceEditor_First {
            get {
                return ResourceManager.GetString("RecurrenceEditor_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fourth.
        /// </summary>
        public static string RecurrenceEditor_Fourth {
            get {
                return ResourceManager.GetString("RecurrenceEditor_Fourth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        public static string RecurrenceEditor_Last {
            get {
                return ResourceManager.GetString("RecurrenceEditor_Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string RecurrenceEditor_Month {
            get {
                return ResourceManager.GetString("RecurrenceEditor_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MonthExpander.
        /// </summary>
        public static string RecurrenceEditor_MonthExpander {
            get {
                return ResourceManager.GetString("RecurrenceEditor_MonthExpander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        public static string RecurrenceEditor_Monthly {
            get {
                return ResourceManager.GetString("RecurrenceEditor_Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MonthPosition.
        /// </summary>
        public static string RecurrenceEditor_MonthPosition {
            get {
                return ResourceManager.GetString("RecurrenceEditor_MonthPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Months.
        /// </summary>
        public static string RecurrenceEditor_Months {
            get {
                return ResourceManager.GetString("RecurrenceEditor_Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MonthWeek.
        /// </summary>
        public static string RecurrenceEditor_MonthWeek {
            get {
                return ResourceManager.GetString("RecurrenceEditor_MonthWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        public static string RecurrenceEditor_Never {
            get {
                return ResourceManager.GetString("RecurrenceEditor_Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string RecurrenceEditor_None {
            get {
                return ResourceManager.GetString("RecurrenceEditor_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string RecurrenceEditor_On {
            get {
                return ResourceManager.GetString("RecurrenceEditor_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OnDay.
        /// </summary>
        public static string RecurrenceEditor_OnDay {
            get {
                return ResourceManager.GetString("RecurrenceEditor_OnDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat.
        /// </summary>
        public static string RecurrenceEditor_Repeat {
            get {
                return ResourceManager.GetString("RecurrenceEditor_Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RepeatEvery.
        /// </summary>
        public static string RecurrenceEditor_RepeatEvery {
            get {
                return ResourceManager.GetString("RecurrenceEditor_RepeatEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RepeatInterval.
        /// </summary>
        public static string RecurrenceEditor_RepeatInterval {
            get {
                return ResourceManager.GetString("RecurrenceEditor_RepeatInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second.
        /// </summary>
        public static string RecurrenceEditor_Second {
            get {
                return ResourceManager.GetString("RecurrenceEditor_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SummaryDay.
        /// </summary>
        public static string RecurrenceEditor_SummaryDay {
            get {
                return ResourceManager.GetString("RecurrenceEditor_SummaryDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SummaryMonth.
        /// </summary>
        public static string RecurrenceEditor_SummaryMonth {
            get {
                return ResourceManager.GetString("RecurrenceEditor_SummaryMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SummaryOn.
        /// </summary>
        public static string RecurrenceEditor_SummaryOn {
            get {
                return ResourceManager.GetString("RecurrenceEditor_SummaryOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SummaryRepeat.
        /// </summary>
        public static string RecurrenceEditor_SummaryRepeat {
            get {
                return ResourceManager.GetString("RecurrenceEditor_SummaryRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SummaryTimes.
        /// </summary>
        public static string RecurrenceEditor_SummaryTimes {
            get {
                return ResourceManager.GetString("RecurrenceEditor_SummaryTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SummaryUntil.
        /// </summary>
        public static string RecurrenceEditor_SummaryUntil {
            get {
                return ResourceManager.GetString("RecurrenceEditor_SummaryUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SummaryWeek.
        /// </summary>
        public static string RecurrenceEditor_SummaryWeek {
            get {
                return ResourceManager.GetString("RecurrenceEditor_SummaryWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SummaryYear.
        /// </summary>
        public static string RecurrenceEditor_SummaryYear {
            get {
                return ResourceManager.GetString("RecurrenceEditor_SummaryYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third.
        /// </summary>
        public static string RecurrenceEditor_Third {
            get {
                return ResourceManager.GetString("RecurrenceEditor_Third", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Until.
        /// </summary>
        public static string RecurrenceEditor_Until {
            get {
                return ResourceManager.GetString("RecurrenceEditor_Until", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        public static string RecurrenceEditor_Weekly {
            get {
                return ResourceManager.GetString("RecurrenceEditor_Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weeks.
        /// </summary>
        public static string RecurrenceEditor_Weeks {
            get {
                return ResourceManager.GetString("RecurrenceEditor_Weeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YearExpander.
        /// </summary>
        public static string RecurrenceEditor_YearExpander {
            get {
                return ResourceManager.GetString("RecurrenceEditor_YearExpander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yearly.
        /// </summary>
        public static string RecurrenceEditor_Yearly {
            get {
                return ResourceManager.GetString("RecurrenceEditor_Yearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years.
        /// </summary>
        public static string RecurrenceEditor_Years {
            get {
                return ResourceManager.GetString("RecurrenceEditor_Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align.
        /// </summary>
        public static string RichTextEditor_Align {
            get {
                return ResourceManager.GetString("RichTextEditor_Align", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alignments.
        /// </summary>
        public static string RichTextEditor_Alignments {
            get {
                return ResourceManager.GetString("RichTextEditor_Alignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlignmentsDropDownCenter.
        /// </summary>
        public static string RichTextEditor_AlignmentsDropDownCenter {
            get {
                return ResourceManager.GetString("RichTextEditor_AlignmentsDropDownCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlignmentsDropDownJustify.
        /// </summary>
        public static string RichTextEditor_AlignmentsDropDownJustify {
            get {
                return ResourceManager.GetString("RichTextEditor_AlignmentsDropDownJustify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlignmentsDropDownLeft.
        /// </summary>
        public static string RichTextEditor_AlignmentsDropDownLeft {
            get {
                return ResourceManager.GetString("RichTextEditor_AlignmentsDropDownLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlignmentsDropDownRight.
        /// </summary>
        public static string RichTextEditor_AlignmentsDropDownRight {
            get {
                return ResourceManager.GetString("RichTextEditor_AlignmentsDropDownRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlternateHeader.
        /// </summary>
        public static string RichTextEditor_AlternateHeader {
            get {
                return ResourceManager.GetString("RichTextEditor_AlternateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AltText.
        /// </summary>
        public static string RichTextEditor_AltText {
            get {
                return ResourceManager.GetString("RichTextEditor_AltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BackgroundColor.
        /// </summary>
        public static string RichTextEditor_BackgroundColor {
            get {
                return ResourceManager.GetString("RichTextEditor_BackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold.
        /// </summary>
        public static string RichTextEditor_Bold {
            get {
                return ResourceManager.GetString("RichTextEditor_Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string RichTextEditor_Browse {
            get {
                return ResourceManager.GetString("RichTextEditor_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caption.
        /// </summary>
        public static string RichTextEditor_Caption {
            get {
                return ResourceManager.GetString("RichTextEditor_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cellpadding.
        /// </summary>
        public static string RichTextEditor_Cellpadding {
            get {
                return ResourceManager.GetString("RichTextEditor_Cellpadding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cellspacing.
        /// </summary>
        public static string RichTextEditor_Cellspacing {
            get {
                return ResourceManager.GetString("RichTextEditor_Cellspacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CleanFormat.
        /// </summary>
        public static string RichTextEditor_CleanFormat {
            get {
                return ResourceManager.GetString("RichTextEditor_CleanFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClearAll.
        /// </summary>
        public static string RichTextEditor_ClearAll {
            get {
                return ResourceManager.GetString("RichTextEditor_ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClearFormat.
        /// </summary>
        public static string RichTextEditor_ClearFormat {
            get {
                return ResourceManager.GetString("RichTextEditor_ClearFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns.
        /// </summary>
        public static string RichTextEditor_Columns {
            get {
                return ResourceManager.GetString("RichTextEditor_Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string RichTextEditor_Copy {
            get {
                return ResourceManager.GetString("RichTextEditor_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateLink.
        /// </summary>
        public static string RichTextEditor_CreateLink {
            get {
                return ResourceManager.GetString("RichTextEditor_CreateLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateTable.
        /// </summary>
        public static string RichTextEditor_CreateTable {
            get {
                return ResourceManager.GetString("RichTextEditor_CreateTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string RichTextEditor_Cut {
            get {
                return ResourceManager.GetString("RichTextEditor_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteColumn.
        /// </summary>
        public static string RichTextEditor_DeleteColumn {
            get {
                return ResourceManager.GetString("RichTextEditor_DeleteColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteRow.
        /// </summary>
        public static string RichTextEditor_DeleteRow {
            get {
                return ResourceManager.GetString("RichTextEditor_DeleteRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DialogCancel.
        /// </summary>
        public static string RichTextEditor_DialogCancel {
            get {
                return ResourceManager.GetString("RichTextEditor_DialogCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DialogInsert.
        /// </summary>
        public static string RichTextEditor_DialogInsert {
            get {
                return ResourceManager.GetString("RichTextEditor_DialogInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DialogUpdate.
        /// </summary>
        public static string RichTextEditor_DialogUpdate {
            get {
                return ResourceManager.GetString("RichTextEditor_DialogUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimension.
        /// </summary>
        public static string RichTextEditor_Dimension {
            get {
                return ResourceManager.GetString("RichTextEditor_Dimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        public static string RichTextEditor_Display {
            get {
                return ResourceManager.GetString("RichTextEditor_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditImageHeader.
        /// </summary>
        public static string RichTextEditor_EditImageHeader {
            get {
                return ResourceManager.GetString("RichTextEditor_EditImageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditLink.
        /// </summary>
        public static string RichTextEditor_EditLink {
            get {
                return ResourceManager.GetString("RichTextEditor_EditLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FontColor.
        /// </summary>
        public static string RichTextEditor_FontColor {
            get {
                return ResourceManager.GetString("RichTextEditor_FontColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FontName.
        /// </summary>
        public static string RichTextEditor_FontName {
            get {
                return ResourceManager.GetString("RichTextEditor_FontName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FontSize.
        /// </summary>
        public static string RichTextEditor_FontSize {
            get {
                return ResourceManager.GetString("RichTextEditor_FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formats.
        /// </summary>
        public static string RichTextEditor_Formats {
            get {
                return ResourceManager.GetString("RichTextEditor_Formats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullscreen.
        /// </summary>
        public static string RichTextEditor_Fullscreen {
            get {
                return ResourceManager.GetString("RichTextEditor_Fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string RichTextEditor_Image {
            get {
                return ResourceManager.GetString("RichTextEditor_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImageAlternateText.
        /// </summary>
        public static string RichTextEditor_ImageAlternateText {
            get {
                return ResourceManager.GetString("RichTextEditor_ImageAlternateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImageCaption.
        /// </summary>
        public static string RichTextEditor_ImageCaption {
            get {
                return ResourceManager.GetString("RichTextEditor_ImageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImageDeviceUploadMessage.
        /// </summary>
        public static string RichTextEditor_ImageDeviceUploadMessage {
            get {
                return ResourceManager.GetString("RichTextEditor_ImageDeviceUploadMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImageDisplayDropDownBreak.
        /// </summary>
        public static string RichTextEditor_ImageDisplayDropDownBreak {
            get {
                return ResourceManager.GetString("RichTextEditor_ImageDisplayDropDownBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImageDisplayDropDownInline.
        /// </summary>
        public static string RichTextEditor_ImageDisplayDropDownInline {
            get {
                return ResourceManager.GetString("RichTextEditor_ImageDisplayDropDownInline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImageHeader.
        /// </summary>
        public static string RichTextEditor_ImageHeader {
            get {
                return ResourceManager.GetString("RichTextEditor_ImageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImageHeight.
        /// </summary>
        public static string RichTextEditor_ImageHeight {
            get {
                return ResourceManager.GetString("RichTextEditor_ImageHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImageInsertLinkHeader.
        /// </summary>
        public static string RichTextEditor_ImageInsertLinkHeader {
            get {
                return ResourceManager.GetString("RichTextEditor_ImageInsertLinkHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImageLinkHeader.
        /// </summary>
        public static string RichTextEditor_ImageLinkHeader {
            get {
                return ResourceManager.GetString("RichTextEditor_ImageLinkHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImageSizeHeader.
        /// </summary>
        public static string RichTextEditor_ImageSizeHeader {
            get {
                return ResourceManager.GetString("RichTextEditor_ImageSizeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImageUploadMessage.
        /// </summary>
        public static string RichTextEditor_ImageUploadMessage {
            get {
                return ResourceManager.GetString("RichTextEditor_ImageUploadMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImageUrl.
        /// </summary>
        public static string RichTextEditor_ImageUrl {
            get {
                return ResourceManager.GetString("RichTextEditor_ImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImageWidth.
        /// </summary>
        public static string RichTextEditor_ImageWidth {
            get {
                return ResourceManager.GetString("RichTextEditor_ImageWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indent.
        /// </summary>
        public static string RichTextEditor_Indent {
            get {
                return ResourceManager.GetString("RichTextEditor_Indent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InsertCode.
        /// </summary>
        public static string RichTextEditor_InsertCode {
            get {
                return ResourceManager.GetString("RichTextEditor_InsertCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InsertColumnLeft.
        /// </summary>
        public static string RichTextEditor_InsertColumnLeft {
            get {
                return ResourceManager.GetString("RichTextEditor_InsertColumnLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InsertColumnRight.
        /// </summary>
        public static string RichTextEditor_InsertColumnRight {
            get {
                return ResourceManager.GetString("RichTextEditor_InsertColumnRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InsertLink.
        /// </summary>
        public static string RichTextEditor_InsertLink {
            get {
                return ResourceManager.GetString("RichTextEditor_InsertLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InsertRowAfter.
        /// </summary>
        public static string RichTextEditor_InsertRowAfter {
            get {
                return ResourceManager.GetString("RichTextEditor_InsertRowAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InsertRowBefore.
        /// </summary>
        public static string RichTextEditor_InsertRowBefore {
            get {
                return ResourceManager.GetString("RichTextEditor_InsertRowBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InsertTableBtn.
        /// </summary>
        public static string RichTextEditor_InsertTableBtn {
            get {
                return ResourceManager.GetString("RichTextEditor_InsertTableBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italic.
        /// </summary>
        public static string RichTextEditor_Italic {
            get {
                return ResourceManager.GetString("RichTextEditor_Italic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JustifyCenter.
        /// </summary>
        public static string RichTextEditor_JustifyCenter {
            get {
                return ResourceManager.GetString("RichTextEditor_JustifyCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JustifyFull.
        /// </summary>
        public static string RichTextEditor_JustifyFull {
            get {
                return ResourceManager.GetString("RichTextEditor_JustifyFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JustifyLeft.
        /// </summary>
        public static string RichTextEditor_JustifyLeft {
            get {
                return ResourceManager.GetString("RichTextEditor_JustifyLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JustifyRight.
        /// </summary>
        public static string RichTextEditor_JustifyRight {
            get {
                return ResourceManager.GetString("RichTextEditor_JustifyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeepFormat.
        /// </summary>
        public static string RichTextEditor_KeepFormat {
            get {
                return ResourceManager.GetString("RichTextEditor_KeepFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LinkHeader.
        /// </summary>
        public static string RichTextEditor_LinkHeader {
            get {
                return ResourceManager.GetString("RichTextEditor_LinkHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LinkOpenInNewWindow.
        /// </summary>
        public static string RichTextEditor_LinkOpenInNewWindow {
            get {
                return ResourceManager.GetString("RichTextEditor_LinkOpenInNewWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LinkText.
        /// </summary>
        public static string RichTextEditor_LinkText {
            get {
                return ResourceManager.GetString("RichTextEditor_LinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LinkTitle.
        /// </summary>
        public static string RichTextEditor_LinkTitle {
            get {
                return ResourceManager.GetString("RichTextEditor_LinkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LinkTooltipLabel.
        /// </summary>
        public static string RichTextEditor_LinkTooltipLabel {
            get {
                return ResourceManager.GetString("RichTextEditor_LinkTooltipLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LinkUrl.
        /// </summary>
        public static string RichTextEditor_LinkUrl {
            get {
                return ResourceManager.GetString("RichTextEditor_LinkUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LinkWebUrl.
        /// </summary>
        public static string RichTextEditor_LinkWebUrl {
            get {
                return ResourceManager.GetString("RichTextEditor_LinkWebUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LowerCase.
        /// </summary>
        public static string RichTextEditor_LowerCase {
            get {
                return ResourceManager.GetString("RichTextEditor_LowerCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximize.
        /// </summary>
        public static string RichTextEditor_Maximize {
            get {
                return ResourceManager.GetString("RichTextEditor_Maximize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MdImageLink.
        /// </summary>
        public static string RichTextEditor_MdImageLink {
            get {
                return ResourceManager.GetString("RichTextEditor_MdImageLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        public static string RichTextEditor_Minimize {
            get {
                return ResourceManager.GetString("RichTextEditor_Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenLink.
        /// </summary>
        public static string RichTextEditor_OpenLink {
            get {
                return ResourceManager.GetString("RichTextEditor_OpenLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderedList.
        /// </summary>
        public static string RichTextEditor_OrderedList {
            get {
                return ResourceManager.GetString("RichTextEditor_OrderedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outdent.
        /// </summary>
        public static string RichTextEditor_Outdent {
            get {
                return ResourceManager.GetString("RichTextEditor_Outdent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string RichTextEditor_Paste {
            get {
                return ResourceManager.GetString("RichTextEditor_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PasteDialogCancel.
        /// </summary>
        public static string RichTextEditor_PasteDialogCancel {
            get {
                return ResourceManager.GetString("RichTextEditor_PasteDialogCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PasteDialogOk.
        /// </summary>
        public static string RichTextEditor_PasteDialogOk {
            get {
                return ResourceManager.GetString("RichTextEditor_PasteDialogOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PasteFormat.
        /// </summary>
        public static string RichTextEditor_PasteFormat {
            get {
                return ResourceManager.GetString("RichTextEditor_PasteFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PasteFormatContent.
        /// </summary>
        public static string RichTextEditor_PasteFormatContent {
            get {
                return ResourceManager.GetString("RichTextEditor_PasteFormatContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlainText.
        /// </summary>
        public static string RichTextEditor_PlainText {
            get {
                return ResourceManager.GetString("RichTextEditor_PlainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string RichTextEditor_Preview {
            get {
                return ResourceManager.GetString("RichTextEditor_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string RichTextEditor_Print {
            get {
                return ResourceManager.GetString("RichTextEditor_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string RichTextEditor_Redo {
            get {
                return ResourceManager.GetString("RichTextEditor_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string RichTextEditor_Remove {
            get {
                return ResourceManager.GetString("RichTextEditor_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RemoveLink.
        /// </summary>
        public static string RichTextEditor_RemoveLink {
            get {
                return ResourceManager.GetString("RichTextEditor_RemoveLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RemoveTable.
        /// </summary>
        public static string RichTextEditor_RemoveTable {
            get {
                return ResourceManager.GetString("RichTextEditor_RemoveTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        public static string RichTextEditor_Replace {
            get {
                return ResourceManager.GetString("RichTextEditor_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows.
        /// </summary>
        public static string RichTextEditor_Rows {
            get {
                return ResourceManager.GetString("RichTextEditor_Rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sourcecode.
        /// </summary>
        public static string RichTextEditor_Sourcecode {
            get {
                return ResourceManager.GetString("RichTextEditor_Sourcecode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strikethrough.
        /// </summary>
        public static string RichTextEditor_Strikethrough {
            get {
                return ResourceManager.GetString("RichTextEditor_Strikethrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Styles.
        /// </summary>
        public static string RichTextEditor_Styles {
            get {
                return ResourceManager.GetString("RichTextEditor_Styles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscript.
        /// </summary>
        public static string RichTextEditor_Subscript {
            get {
                return ResourceManager.GetString("RichTextEditor_Subscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superscript.
        /// </summary>
        public static string RichTextEditor_Superscript {
            get {
                return ResourceManager.GetString("RichTextEditor_Superscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableCellBackground.
        /// </summary>
        public static string RichTextEditor_TableCellBackground {
            get {
                return ResourceManager.GetString("RichTextEditor_TableCellBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableCellHorizontalAlign.
        /// </summary>
        public static string RichTextEditor_TableCellHorizontalAlign {
            get {
                return ResourceManager.GetString("RichTextEditor_TableCellHorizontalAlign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableCellVerticalAlign.
        /// </summary>
        public static string RichTextEditor_TableCellVerticalAlign {
            get {
                return ResourceManager.GetString("RichTextEditor_TableCellVerticalAlign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableColText.
        /// </summary>
        public static string RichTextEditor_TableColText {
            get {
                return ResourceManager.GetString("RichTextEditor_TableColText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableColumns.
        /// </summary>
        public static string RichTextEditor_TableColumns {
            get {
                return ResourceManager.GetString("RichTextEditor_TableColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TabledialogHeader.
        /// </summary>
        public static string RichTextEditor_TabledialogHeader {
            get {
                return ResourceManager.GetString("RichTextEditor_TabledialogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableEditHeader.
        /// </summary>
        public static string RichTextEditor_TableEditHeader {
            get {
                return ResourceManager.GetString("RichTextEditor_TableEditHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableEditProperties.
        /// </summary>
        public static string RichTextEditor_TableEditProperties {
            get {
                return ResourceManager.GetString("RichTextEditor_TableEditProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableHeader.
        /// </summary>
        public static string RichTextEditor_TableHeader {
            get {
                return ResourceManager.GetString("RichTextEditor_TableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableHeadingText.
        /// </summary>
        public static string RichTextEditor_TableHeadingText {
            get {
                return ResourceManager.GetString("RichTextEditor_TableHeadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableInsertColumnDropDownDelete.
        /// </summary>
        public static string RichTextEditor_TableInsertColumnDropDownDelete {
            get {
                return ResourceManager.GetString("RichTextEditor_TableInsertColumnDropDownDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableInsertColumnDropDownLeft.
        /// </summary>
        public static string RichTextEditor_TableInsertColumnDropDownLeft {
            get {
                return ResourceManager.GetString("RichTextEditor_TableInsertColumnDropDownLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableInsertColumnDropDownRight.
        /// </summary>
        public static string RichTextEditor_TableInsertColumnDropDownRight {
            get {
                return ResourceManager.GetString("RichTextEditor_TableInsertColumnDropDownRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableInsertRowDropDownAfter.
        /// </summary>
        public static string RichTextEditor_TableInsertRowDropDownAfter {
            get {
                return ResourceManager.GetString("RichTextEditor_TableInsertRowDropDownAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableInsertRowDropDownBefore.
        /// </summary>
        public static string RichTextEditor_TableInsertRowDropDownBefore {
            get {
                return ResourceManager.GetString("RichTextEditor_TableInsertRowDropDownBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableInsertRowDropDownDelete.
        /// </summary>
        public static string RichTextEditor_TableInsertRowDropDownDelete {
            get {
                return ResourceManager.GetString("RichTextEditor_TableInsertRowDropDownDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableRemove.
        /// </summary>
        public static string RichTextEditor_TableRemove {
            get {
                return ResourceManager.GetString("RichTextEditor_TableRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableRows.
        /// </summary>
        public static string RichTextEditor_TableRows {
            get {
                return ResourceManager.GetString("RichTextEditor_TableRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableStylesDropDownAlternateRows.
        /// </summary>
        public static string RichTextEditor_TableStylesDropDownAlternateRows {
            get {
                return ResourceManager.GetString("RichTextEditor_TableStylesDropDownAlternateRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableStylesDropDownDashedBorder.
        /// </summary>
        public static string RichTextEditor_TableStylesDropDownDashedBorder {
            get {
                return ResourceManager.GetString("RichTextEditor_TableStylesDropDownDashedBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableVerticalAlignDropDownBottom.
        /// </summary>
        public static string RichTextEditor_TableVerticalAlignDropDownBottom {
            get {
                return ResourceManager.GetString("RichTextEditor_TableVerticalAlignDropDownBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableVerticalAlignDropDownMiddle.
        /// </summary>
        public static string RichTextEditor_TableVerticalAlignDropDownMiddle {
            get {
                return ResourceManager.GetString("RichTextEditor_TableVerticalAlignDropDownMiddle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableVerticalAlignDropDownTop.
        /// </summary>
        public static string RichTextEditor_TableVerticalAlignDropDownTop {
            get {
                return ResourceManager.GetString("RichTextEditor_TableVerticalAlignDropDownTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableWidth.
        /// </summary>
        public static string RichTextEditor_TableWidth {
            get {
                return ResourceManager.GetString("RichTextEditor_TableWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextPlaceholder.
        /// </summary>
        public static string RichTextEditor_TextPlaceholder {
            get {
                return ResourceManager.GetString("RichTextEditor_TextPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underline.
        /// </summary>
        public static string RichTextEditor_Underline {
            get {
                return ResourceManager.GetString("RichTextEditor_Underline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string RichTextEditor_Undo {
            get {
                return ResourceManager.GetString("RichTextEditor_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnorderedList.
        /// </summary>
        public static string RichTextEditor_UnorderedList {
            get {
                return ResourceManager.GetString("RichTextEditor_UnorderedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpperCase.
        /// </summary>
        public static string RichTextEditor_UpperCase {
            get {
                return ResourceManager.GetString("RichTextEditor_UpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewside.
        /// </summary>
        public static string RichTextEditor_Viewside {
            get {
                return ResourceManager.GetString("RichTextEditor_Viewside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddTitle.
        /// </summary>
        public static string Schedule_AddTitle {
            get {
                return ResourceManager.GetString("Schedule_AddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agenda.
        /// </summary>
        public static string Schedule_Agenda {
            get {
                return ResourceManager.GetString("Schedule_Agenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        public static string Schedule_Alert {
            get {
                return ResourceManager.GetString("Schedule_Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AllDay.
        /// </summary>
        public static string Schedule_AllDay {
            get {
                return ResourceManager.GetString("Schedule_AllDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BeginForm.
        /// </summary>
        public static string Schedule_BeginForm {
            get {
                return ResourceManager.GetString("Schedule_BeginForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlockAlert.
        /// </summary>
        public static string Schedule_BlockAlert {
            get {
                return ResourceManager.GetString("Schedule_BlockAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Schedule_Cancel {
            get {
                return ResourceManager.GetString("Schedule_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CancelButton.
        /// </summary>
        public static string Schedule_CancelButton {
            get {
                return ResourceManager.GetString("Schedule_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Schedule_Close {
            get {
                return ResourceManager.GetString("Schedule_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateError.
        /// </summary>
        public static string Schedule_CreateError {
            get {
                return ResourceManager.GetString("Schedule_CreateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateEvent.
        /// </summary>
        public static string Schedule_CreateEvent {
            get {
                return ResourceManager.GetString("Schedule_CreateEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Schedule_Day {
            get {
                return ResourceManager.GetString("Schedule_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Schedule_Delete {
            get {
                return ResourceManager.GetString("Schedule_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteButton.
        /// </summary>
        public static string Schedule_DeleteButton {
            get {
                return ResourceManager.GetString("Schedule_DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteContent.
        /// </summary>
        public static string Schedule_DeleteContent {
            get {
                return ResourceManager.GetString("Schedule_DeleteContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteEvent.
        /// </summary>
        public static string Schedule_DeleteEvent {
            get {
                return ResourceManager.GetString("Schedule_DeleteEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteMultipleContent.
        /// </summary>
        public static string Schedule_DeleteMultipleContent {
            get {
                return ResourceManager.GetString("Schedule_DeleteMultipleContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteMultipleEvent.
        /// </summary>
        public static string Schedule_DeleteMultipleEvent {
            get {
                return ResourceManager.GetString("Schedule_DeleteMultipleEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteSeries.
        /// </summary>
        public static string Schedule_DeleteSeries {
            get {
                return ResourceManager.GetString("Schedule_DeleteSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteTitle.
        /// </summary>
        public static string Schedule_DeleteTitle {
            get {
                return ResourceManager.GetString("Schedule_DeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Schedule_Description {
            get {
                return ResourceManager.GetString("Schedule_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Schedule_Edit {
            get {
                return ResourceManager.GetString("Schedule_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditContent.
        /// </summary>
        public static string Schedule_EditContent {
            get {
                return ResourceManager.GetString("Schedule_EditContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditEvent.
        /// </summary>
        public static string Schedule_EditEvent {
            get {
                return ResourceManager.GetString("Schedule_EditEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditFollowingEvent.
        /// </summary>
        public static string Schedule_EditFollowingEvent {
            get {
                return ResourceManager.GetString("Schedule_EditFollowingEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditRecurrence.
        /// </summary>
        public static string Schedule_EditRecurrence {
            get {
                return ResourceManager.GetString("Schedule_EditRecurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditSeries.
        /// </summary>
        public static string Schedule_EditSeries {
            get {
                return ResourceManager.GetString("Schedule_EditSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditTitle.
        /// </summary>
        public static string Schedule_EditTitle {
            get {
                return ResourceManager.GetString("Schedule_EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmptyContainer.
        /// </summary>
        public static string Schedule_EmptyContainer {
            get {
                return ResourceManager.GetString("Schedule_EmptyContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string Schedule_End {
            get {
                return ResourceManager.GetString("Schedule_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndAt.
        /// </summary>
        public static string Schedule_EndAt {
            get {
                return ResourceManager.GetString("Schedule_EndAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndTimezone.
        /// </summary>
        public static string Schedule_EndTimezone {
            get {
                return ResourceManager.GetString("Schedule_EndTimezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidDateError.
        /// </summary>
        public static string Schedule_InvalidDateError {
            get {
                return ResourceManager.GetString("Schedule_InvalidDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Schedule_Location {
            get {
                return ResourceManager.GetString("Schedule_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Schedule_Month {
            get {
                return ResourceManager.GetString("Schedule_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MonthAgenda.
        /// </summary>
        public static string Schedule_MonthAgenda {
            get {
                return ResourceManager.GetString("Schedule_MonthAgenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string Schedule_More {
            get {
                return ResourceManager.GetString("Schedule_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MoreDetails.
        /// </summary>
        public static string Schedule_MoreDetails {
            get {
                return ResourceManager.GetString("Schedule_MoreDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewEvent.
        /// </summary>
        public static string Schedule_NewEvent {
            get {
                return ResourceManager.GetString("Schedule_NewEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Schedule_next {
            get {
                return ResourceManager.GetString("Schedule_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Schedule_No {
            get {
                return ResourceManager.GetString("Schedule_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoEvents.
        /// </summary>
        public static string Schedule_NoEvents {
            get {
                return ResourceManager.GetString("Schedule_NoEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoTitle.
        /// </summary>
        public static string Schedule_NoTitle {
            get {
                return ResourceManager.GetString("Schedule_NoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurrence.
        /// </summary>
        public static string Schedule_Occurrence {
            get {
                return ResourceManager.GetString("Schedule_Occurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Schedule_Ok {
            get {
                return ResourceManager.GetString("Schedule_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Schedule_Previous {
            get {
                return ResourceManager.GetString("Schedule_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurrence.
        /// </summary>
        public static string Schedule_Recurrence {
            get {
                return ResourceManager.GetString("Schedule_Recurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat.
        /// </summary>
        public static string Schedule_Repeat {
            get {
                return ResourceManager.GetString("Schedule_Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeats.
        /// </summary>
        public static string Schedule_Repeats {
            get {
                return ResourceManager.GetString("Schedule_Repeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SameDayAlert.
        /// </summary>
        public static string Schedule_SameDayAlert {
            get {
                return ResourceManager.GetString("Schedule_SameDayAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Schedule_Save {
            get {
                return ResourceManager.GetString("Schedule_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaveButton.
        /// </summary>
        public static string Schedule_SaveButton {
            get {
                return ResourceManager.GetString("Schedule_SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectedItems.
        /// </summary>
        public static string Schedule_SelectedItems {
            get {
                return ResourceManager.GetString("Schedule_SelectedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series.
        /// </summary>
        public static string Schedule_Series {
            get {
                return ResourceManager.GetString("Schedule_Series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SeriesChangeAlert.
        /// </summary>
        public static string Schedule_SeriesChangeAlert {
            get {
                return ResourceManager.GetString("Schedule_SeriesChangeAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Schedule_Start {
            get {
                return ResourceManager.GetString("Schedule_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartEndError.
        /// </summary>
        public static string Schedule_StartEndError {
            get {
                return ResourceManager.GetString("Schedule_StartEndError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartTimezone.
        /// </summary>
        public static string Schedule_StartTimezone {
            get {
                return ResourceManager.GetString("Schedule_StartTimezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Schedule_Subject {
            get {
                return ResourceManager.GetString("Schedule_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimelineDay.
        /// </summary>
        public static string Schedule_TimelineDay {
            get {
                return ResourceManager.GetString("Schedule_TimelineDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimelineMonth.
        /// </summary>
        public static string Schedule_TimelineMonth {
            get {
                return ResourceManager.GetString("Schedule_TimelineMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimelineWeek.
        /// </summary>
        public static string Schedule_TimelineWeek {
            get {
                return ResourceManager.GetString("Schedule_TimelineWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimelineWorkWeek.
        /// </summary>
        public static string Schedule_TimelineWorkWeek {
            get {
                return ResourceManager.GetString("Schedule_TimelineWorkWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimelineYear.
        /// </summary>
        public static string Schedule_TimelineYear {
            get {
                return ResourceManager.GetString("Schedule_TimelineYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timezone.
        /// </summary>
        public static string Schedule_Timezone {
            get {
                return ResourceManager.GetString("Schedule_Timezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Schedule_Title {
            get {
                return ResourceManager.GetString("Schedule_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Schedule_Today {
            get {
                return ResourceManager.GetString("Schedule_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        public static string Schedule_Week {
            get {
                return ResourceManager.GetString("Schedule_Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WeekAgenda.
        /// </summary>
        public static string Schedule_WeekAgenda {
            get {
                return ResourceManager.GetString("Schedule_WeekAgenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkWeek.
        /// </summary>
        public static string Schedule_WorkWeek {
            get {
                return ResourceManager.GetString("Schedule_WorkWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkWeekAgenda.
        /// </summary>
        public static string Schedule_WorkWeekAgenda {
            get {
                return ResourceManager.GetString("Schedule_WorkWeekAgenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WrongPattern.
        /// </summary>
        public static string Schedule_WrongPattern {
            get {
                return ResourceManager.GetString("Schedule_WrongPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Schedule_Yes {
            get {
                return ResourceManager.GetString("Schedule_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease.
        /// </summary>
        public static string Slider_DecrementTitle {
            get {
                return ResourceManager.GetString("Slider_DecrementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase.
        /// </summary>
        public static string Slider_IncrementTitle {
            get {
                return ResourceManager.GetString("Slider_IncrementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CloseButtonTitle.
        /// </summary>
        public static string Tab_CloseButtonTitle {
            get {
                return ResourceManager.GetString("Tab_CloseButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Toast_Close {
            get {
                return ResourceManager.GetString("Toast_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        public static string Toast_Closed {
            get {
                return ResourceManager.GetString("Toast_Closed", resourceCulture);
            }
        }
    }
}
